### ISSUE TITLE
How to convert Whisper Large v2

### ISSUE THREAD

**Issue by hotmeatballs** [xenova/transformers.js#102]
Hello! 

How to convert whisper-large-v2 model to onnx?

I'm using this command  

`python3.9 -m scripts.convert --model_id whisper-large-v2 --quantize --task automatic-speech-recognition`

But when i try to connect the converted model i get the following error:
`Error: File not found. Could not locate "encoder_model.onnx".`

Thank you!

**Comment by xenova** [comment]
Unfortunately, I am unable to perform the conversion on my side to test because I run out of RAM, which is related to https://github.com/huggingface/optimum/issues/1012.

Is there a specific reason you need the large v2 version of the model? I don't think that would be suitable for use in a browser environment. Will medium or smaller work for your use case?

**Comment by hotmeatballs** [comment]
I'm using it on server side(nodejs) and difference between large and base model is big...

**Comment by hotmeatballs** [comment]
@xenova maybe we are converting with wrong parameters?

**Comment by xenova** [comment]
@hotmeatballs If you'd like, you can try convert with the latest conversion script: https://huggingface.co/docs/transformers.js/custom_usage#convert-your-models-to-onnx

You may need over 25GB of RAM to do the conversion, though. Let me know if you are able to do this.

**Comment by xenova** [comment]
Update: I was able to export the model by skipping validation (which caused OOM issues).

Here's the converted model: https://huggingface.co/Xenova/whisper-large-v2/tree/main (with weights in the "onnx" folder). You should now be able to use it with Transformers.js.

NOTE: You'll only be able to use the quantized model (default) for now until we support the external data format.
