### ISSUE TITLE
Variable embedding length after v2.1.0

### ISSUE THREAD

**Issue by klavinski** [xenova/transformers.js#151]
**Describe the bug**
*A clear and concise description of what the bug is.*

Up to v2.0.2, the length of the embeddings created by 
```tsx
pipeline( "embeddings", "sentence-transformers/all-MiniLM-L6-v2" )
```
was constant. With v2.1.0, 2.1.1 and 2.2.0, the length becomes variable.

**How to reproduce**
*Steps or a minimal working example to reproduce the behavior*

```tsx
const pipe = await pipeline( "embeddings", "sentence-transformers/all-MiniLM-L6-v2" )
const children = ( await pipe( "Children's Literature" ) ).data // Float32Array( 2304 )
const books = ( await pipe( "Books & Literature" ) ).data // Float32Array( 1920 )
```

**Expected behavior**
*A clear and concise description of what you expected to happen.*

With v2.0.2, the result was `Float32Array( 384 )` for both strings.

**Environment**
- Transformers.js version: 2.1.0, 2.1.1 & 2.2.0
- Browser (if applicable): Chrome Version 116.0.5832.0 (Official Build) canary (arm64)
- Operating system (if applicable): macOS 13.3.1 (22E261)

**Comment by xenova** [comment]
Hi there. Yes, this is intentional, and was done to better align with the python library's output. This change was necessary to allow for feature extraction and embedding calculation for models other than sentence-transformers models. For more information, please see the release notes: https://github.com/xenova/transformers.js/releases/tag/2.1.0

To get the old behaviour, you need to pass `{ pooling: "mean", normalize: true }` as additional options to the call function (see the release notes for examples on this).

Let me know if you have any further questions 😇👍

**Comment by klavinski** [comment]
Wonderful, thank you!

I see that `embeddings` as task has been replaced by `feature-extraction` in the [documentation](https://huggingface.co/docs/transformers.js/api/pipelines#module_pipelines.FeatureExtractionPipeline).

Would it make sense to keep the old behaviour for `embeddings`, deprecate it, show a warning?

**Comment by xenova** [comment]
> Would it make sense to keep the old behaviour for embeddings, deprecate it, show a warning?

That could be a good idea (i.e., use mean pooling and normalization by default if using `embeddings`). My only concern would be that there would then be a difference to the python library (see [here](https://github.com/huggingface/transformers/blob/main/src/transformers/pipelines/__init__.py)). Another option would be to add this to the python library - which could be quite useful now that I think of it. I'll bring it up with the transformers team :)

I'll close the issue for now, but feel free to reopen or ask any other questions 👍
