### ISSUE TITLE
Segment Anything Model

### ISSUE THREAD

**Issue by josephrocca** [xenova/transformers.js#163]
**Name of the feature**
Support for SAM: https://huggingface.co/docs/transformers/v4.30.0/model_doc/sam

**Reason for request**
I don't actually have an immediate need for this, but I noticed that [it's on the roadmap](https://twitter.com/xenovacom/status/1645604804582944769) now that SAM is supported in the Python lib, but there wasn't an explicit issue for it, and with the recent release of FastSAM, it seems even more exciting.

**Additional context**

 * FastSAM was just released, which brings inference time down from 2000ms to 40ms: https://github.com/CASIA-IVA-Lab/FastSAM

**Comment by xenova** [comment]
Technically, SAM is already working:

https://github.com/xenova/transformers.js/blob/8d6622ef9bddcd61d325b2cdee5870a16972a4ba/src/models.js#L2201-L2212

via `AutoModelForMaskGeneration`:
https://github.com/xenova/transformers.js/blob/8d6622ef9bddcd61d325b2cdee5870a16972a4ba/src/models.js#L2705-L2708

However, I haven't made it into a `pipeline` yet since the current models are monoliths (https://huggingface.co/models?library=transformers.js&sort=downloads&search=sam) - i.e., no separate encoder and decoder. I made a feature request for this for optimum a few weeks ago, but nothing yet: https://github.com/huggingface/optimum/issues/1078

Once we can reuse the ouput from the encoder, this will become feasible for use in a browser.

**Comment by BjoernRave** [comment]
Is it now theoretically possible to get segment anything running efficiently on a mobile device (maybe even sth like this: https://github.com/IDEA-Research/Grounded-Segment-Anything/tree/main/EfficientSAM#run-grounded-mobilesam-demo) , since I can just import any onnx into transformers-js?
