### ISSUE TITLE
[Feature request] Expand Tokenizer support for Falcon and MPT models

### ISSUE THREAD

**Issue by fozziethebeat** [xenova/transformers.js#164]
**More Tokenizers: MPT and Falcon**

**Reason for request**
Falcon and MPT LLMs are two of the newer top class Open Source Models that have their own customized code for just about everything.  They're likely too complex for serving in transformers.js but HuggingFace's text-generation-interface does a pretty good job for handling the serving for complex models.  But, in many cases it's helpful to still verify that prompts are within the expected token lengths on the client side before sending a request to the server. 

*Why is it important that we add this feature? What is your intended use case? Remember, we are more likely to add support for models/pipelines/tasks that are popular (e.g., many downloads), or contain functionality that does not exist (e.g., new input type).*

Falcon and MPT models are pretty popular and reportedly very capable.  It'd be *great* to be able to tokenize on node.js clients to ensure prompts fit within context limits.

**Additional context**
*Add any other context or screenshots about the feature request here.*

I've tried running tokenization with falcon-7b and got the following errors:

```
Unable to determine content-length from response headers. Will expand buffer when needed.
Unknown tokenizer class "PreTrainedTokenizer", attempting to construct from base class.
Error: Unknown PreTokenizer type: Punctuation
    at PreTokenizer.fromConfig (file:///Users/fozziethebeat/devel/cubrio/copperfield/node_modules/@xenova/transformers/src/tokenizers.js:936:23)
    at file:///Users/fozziethebeat/devel/cubrio/copperfield/node_modules/@xenova/transformers/src/tokenizers.js:1715:70
    at Array.map (<anonymous>)
    at new PreTokenizerSequence (file:///Users/fozziethebeat/devel/cubrio/copperfield/node_modules/@xenova/transformers/src/tokenizers.js:1715:48)
    at PreTokenizer.fromConfig (file:///Users/fozziethebeat/devel/cubrio/copperfield/node_modules/@xenova/transformers/src/tokenizers.js:924:24)
    at new PreTrainedTokenizer (file:///Users/fozziethebeat/devel/cubrio/copperfield/node_modules/@xenova/transformers/src/tokenizers.js:1767:43)
    at AutoTokenizer.from_pretrained (file:///Users/fozziethebeat/devel/cubrio/copperfield/node_modules/@xenova/transformers/src/tokenizers.js:3222:16)
```

Trying to tokenize with mpt-7b I get a result that's more successful but maybe isn't 100% compatible:

```
Unknown tokenizer class "GPTNeoXTokenizer", attempting to construct from base class.
```

**Comment by xenova** [comment]
Sure, I can add this! 👍

**Comment by xenova** [comment]
Work in progress here: https://github.com/xenova/transformers.js/pull/165 👍  They're now both added, and will hopefully merge into main soon. You can use that branch in the meantime if you need it now :) 

One thing to note: Since FalconTokenizer is not yet supported in the python library, they use [`PreTrainedTokenizerFast` as the `tokenizer_class`](https://huggingface.co/tiiuae/falcon-7b/blob/main/tokenizer_config.json). The python library outputs `token_type_ids` by default (whereas this library does not unless the tokenizer specifically outputs it). So, for testing, I've updated the tokenizer_class of `Xenova/falcon-7b` to [`FalconTokenizer` ](https://huggingface.co/Xenova/falcon-7b/blob/main/tokenizer_config.json).  This is only necessary if you need the `token_type_ids`. Otherwise, if you don't need it, you can just use the original tokenizer. For example:
```js
import { AutoTokenizer } from '@xenova/transformers';

let tokenizer = await AutoTokenizer.from_pretrained('tiiuae/falcon-7b');
let model_inputs = await tokenizer("Hello world!");
console.log(model_inputs);
{
    attention_mask : Tensor {
        data: BigInt64Array(3) [1n, 1n, 1n],
        dims: [1, 3],
        size: 3,
        type: "int64"
    },
    input_ids: Tensor {
        data: BigInt64Array(3) [9856n, 1079n, 12n],
	dims: [1, 3],
	size: 3,
	type: "int64"
    },
}
```

**Comment by fozziethebeat** [comment]
Awesome! I'm glad it was a fairly straight forward addition!
