### ISSUE TITLE
[Question] Performance and size of models

### ISSUE THREAD

**Issue by sabatale** [xenova/transformers.js#187]
Great project, tons of potential! I have a general question I thought I may ask. Using the convert.py scripts, I took a Pytorch model and converted it to ONNX. With quantizing, I get a full 428MB model and a 110MB _quantized model. Now how does it work for the user exactly? Does the user automatically download the _quantized one?

Would this be accurate:

- WASM downloaded/loaded (e.g., 15MB)
- Transformers.js runs the core
- Model downloaded/load (e.g., 110MB)
- Model starts and runs
- Result is returned
- (next time it is called, WASM is reloaded and model is cached)

125MB is still quite big for the web: [https://huggingface.co/plopop/industry-classification-api-onnx](https://huggingface.co/plopop/industry-classification-api-onnx)

With something like [https://huggingface.co/Xenova/mobilebert-uncased-mnli](https://huggingface.co/Xenova/mobilebert-uncased-mnli) (27MB), running everything within a worker takes 8-15seconds depending on the input from our end right now - is there any other performance gains that can be saved, or would the only way be to optimize the source model further?

**Comment by xenova** [comment]
>  Does the user automatically download the _quantized one?

Yes, by default, the library uses the quantized versions (simply because of size requirements over the web). To override this (i.e., use the unquantized versions), you can specify `quantized: false` in the loading options. For example:
```js
// Allocation a pipeline for feature extraction, using the unquantized model
const pipe = await pipeline('feature-extraction', 'Xenova/all-MiniLM-L6-v2', {
    quantized: false,
});
```

> Would this be accurate:

Yep that looks about right!

> everything within a worker takes 8-15seconds depending on the input from our end right now
> is there any other performance gains that can be saved, or would the only way be to optimize the source model further?

Can you provide the sample code (and example data) you are using? 8-15 seconds might be the time taken including the model downloading, but once that's done (and the model is cached), inference should be near instant.

**Comment by sabatale** [comment]
Something like this - just to be sure, **env.allowLocalModels = false** prevents the browser from looking for local models (many console warnings otherwise), but does not disable the cache, right?

```
var tr_script = new Blob(["import { env, pipeline } from 'https://cdn.jsdelivr.net/npm/@xenova/transformers@2.3.1';" + 
        " onmessage = async function(e) { " + getClassif.toString() + "; getClassif(e); }"], {type: "text/javascript"});
worker = new Worker(URL.createObjectURL(tr_script), { type: "module" });
worker.postMessage(["classification", input);
worker.onmessage = async function (e) {
  if (e.data[0] === "classification_is_done") {
   ....
  }
}
```

```
async function getClassif(data) {
  var sequence = data[1];

  try {
    var fastModel = "Xenova/mobilebert-uncased-mnli";
    var slowModel = "Xenova/distilbert-base-uncased-mnli";
    var xslowModel = "Xenova/bart-large-mnli";
    env.allowLocalModels = false;

    const startTime = performance.now();
    const textClassifier = await pipeline('zero-shot-classification', fastModel);
    var labels = ["A", "B", ..., "K"];
    const tags = await textClassifier(sequence, labels, { multi_label: false });
    console.log("Classification time:", Math.round((performance.now() - startTime) * 1000) / 1000 + ' ms'); // Always takes 10+ secs

    if (tags) {
      var labels = tags.labels;
      var scores = tags.scores;
      self.postMessage([`classification_is_done`, labels, scores]);
   }
}
```

**Comment by xenova** [comment]
I believe it's because you are constructing the pipeline each time you call `getClassif`. Note that `await pipeline` constructs a new pipeline each time - and in cases where the model is large, the loading of weights and processing of the graph can cause a significant delay.

In your case, you have two simple options to fix this:
1. Move `await pipeline` outside of the `getClassif` function. This will begin loading the model as soon as your worker is created.
2. The other option is to use a singleton class which will lazily create the pipeline, then cache the loaded pipeline. Here's some example code which should work:

```js
// Ensures only one model is created of each type
class Singleton {
    static instance = null;

    static async getInstance(progress_callback = null) {
        if (this.instance === null) {
            this.instance = pipeline("zero-shot-classification", "Xenova/mobilebert-uncased-mnli");
        }

        return this.instance;
    }
}
```
you can then replace any call to `await pipeline` to `await Singleton.getInstance()`, which should only create the pipeline on the first load.

Let me know if you have any other questions 👍
