### ISSUE TITLE
Uncaught ReferenceError: self is not defined

### ISSUE THREAD

**Issue by adarah** [xenova/transformers.js#19]
I'm trying to use this library to run whisper in a browser environment, outside of a webworker, using NextJS. However, because of [this line](https://github.com/xenova/transformers.js/blob/5f9edeb948fadb9218e555dbc7e93d5a11048b5e/src/processors.js#L15), I get an error.

Here's how I triggered it:
```js
      const pipe = await pipeline(
        "automatic-speech-recognition",
        "openai/whisper-base"
      );
      const out = await pipe(
        "https://huggingface.co/datasets/Narsil/asr_dummy/resolve/main/mlk.flac"
      );
```
[Code sandbox](https://codesandbox.io/p/sandbox/elated-surf-p0l8lk?file=%2FREADME.md)

**Comment by xenova** [comment]
Hi there! Yes, this is a known bug with ONNX runtime web (https://github.com/xenova/transformers.js/issues/4#issuecomment-1472436805)

To fix it, you should be able to do this before importing:
```javascript
// 1. Fix "ReferenceError: self is not defined" bug when running directly with node
// https://github.com/microsoft/onnxruntime/issues/13072
global.self = global;

const { pipeline, env } = require('@xenova/transformers')

// 2. Disable spawning worker threads for testing.
// This is done by setting numThreads to 1
env.onnx.wasm.numThreads = 1

// 3. Continue as per usual:
// ...
```

**Comment by adarah** [comment]
Thanks for the quick reply! I didn't have luck with that workaround, but since the issue you linked seems to suggest that this could be related to node/SSR, I managed to get it working by using a dynamic import:
```ts
useEffect(() => {
    async function run() {
      const { pipeline } = await import("@xenova/transformers");
      const pipe = await pipeline(
        "automatic-speech-recognition",
        "openai/whisper-base"
      );
      const out = await pipe(
        "https://huggingface.co/datasets/Narsil/asr_dummy/resolve/main/mlk.flac"
      );
      console.log(out);
    }
    void run();
  }, []);
```

**Comment by xenova** [comment]
Okay nice! Yeah, the library is quite new (and it hasn't been tested across different environments). With more testing and contributions, it will be great to get this "production-ready", if you know what I mean haha.

Just as a side-note, be sure that you only create the pipeline once (the `await pipeline(...)` code), otherwise you might run into some memory issues (like https://github.com/xenova/transformers.js/issues/8). I got this working in the demo by creating a singleton object (/pipeline factory): 
https://github.com/xenova/transformers.js/blob/main/assets/js/worker.js#L47-L69
