### ISSUE TITLE
[Question] Code freezes when bart-large-mnli pipeline called

### ISSUE THREAD

**Issue by eklavyaisabird** [xenova/transformers.js#212]
Hello, when I try to use transformers.js like so: 
```
import { pipeline } from "@xenova/transformers";

let s = "wow i sure do enjoy a good game of sportsball";
let labels = ["sports", "travel", "cooking", "dancing"];

// Allocate a pipeline for sentiment-analysis
try {
  console.log("await pipeline...");
  let pipe = await pipeline("text-classification", "Xenovabart-large-mnli");

  console.log("await out...");
  let out = await pipe(s, labels);

  console.log(out);
} catch (error) {
  console.log(error);
}
```

it freezes on the line   `let pipe = await pipeline("text-classification", "Xenova/bart-large-mnli");`. So it print the "await pipeline..." and then stops.
This only occurs when I try to use a non-default model. 

it's possible that I am using it incorrectly, but the code is pretty much copied from the Huggingface website as you can probably tell. This is in a .js file separate from any of my react code. All of my code for the file is above. It also doesnt print any error.

<img width="214" alt="Screen Shot 2023-07-23 at 6 03 33 PM" src="https://github.com/xenova/transformers.js/assets/77216995/0b083b4a-c93e-4970-a350-139913b471de">

Am I doing it correctly?

**Environment**
- Transformers.js version: not sure
- Operating system (if applicable): MacOS

**Comment by eklavyaisabird** [comment]
Ok, so it wasnt stuck just took really really long. But the result is still unexpected. I expected the output to be the labels from the list I created and the probabilities of each one, instead it just gave me this:

<img width="476" alt="Screen Shot 2023-07-23 at 6 08 26 PM" src="https://github.com/xenova/transformers.js/assets/77216995/fb124019-ef39-4a11-8898-4696031caf30">

**Comment by xenova** [comment]
> Ok, so it wasnt stuck just took really really long. 

The quantized version of [Xenova/bart-large-mnli](https://huggingface.co/Xenova/bart-large-mnli/tree/main/onnx) is ~400MB, and when run for the first time, the model will be downloaded and cached. Subsequent runs (as you'll see if you rerun the file) will be much quicker! The main problem is that there is not any logging (yet)... which I will hopefully get to adding soon :)

> I expected the output to be the labels from the list I created and the probabilities of each one, instead it just gave me this:

I think you are using the incorrect task. You have specified `text-classification` when you are probably wanting to use `zero-shot-classification` (since you are specifying labels). The reason it works for `text-classification` is because under-the-hood, they use the same model.
![image](https://github.com/xenova/transformers.js/assets/26504141/82c03d0f-d1ad-4915-9f83-ef1714f9af69)

**Comment by eklavyaisabird** [comment]
Joshua, you are so helpful. Thank you so much!

**Comment by eklavyaisabird** [comment]
Sorry, one last small thing:

The output of my code using transformers.js shows far more even probabilities than what is displayed on the Facebook/bart-large-mnli docs, even for the same text and labels. for example: this code: 
```import { pipeline } from "@xenova/transformers";

let s = "one day i will see the world!";
let labels = ["travel", "cooking", "dancing"];

try {
  console.log("await pipeline...");
  let pipe = await pipeline(
    "zero-shot-classification",
    "Xenova/bart-large-mnli"
  );

  console.log("await out...");
  let out = await pipe(s, labels);

  console.log(out);
} catch (error) {
  console.log(error);
}

```

Results in this:

<img width="556" alt="Screen Shot 2023-07-23 at 6 36 38 PM" src="https://github.com/xenova/transformers.js/assets/77216995/20584e7b-c403-4913-9456-e5bc8618f042">

But the equivalent code on the docs results in an output that is far more convinced that the text relates to ’travel’:

<img width="612" alt="sequence_to_classify = one day I will see the world" src="https://github.com/xenova/transformers.js/assets/77216995/d17fc98c-1be5-4e69-8ece-7a095c1605b7">

And the same in the real-time example:

<img width="549" alt="Examples" src="https://github.com/xenova/transformers.js/assets/77216995/9f58328c-d474-4063-a6a8-d2debcae5f85">

Is there any particular reason for this?

**Comment by eklavyaisabird** [comment]
removing the exclamation mark from the string resulted in a better but similar result: 
<img width="535" alt="Screen Shot 2023-07-23 at 6 39 42 PM" src="https://github.com/xenova/transformers.js/assets/77216995/077e77bd-6b83-45f5-8b65-5517efe11de5">

**Comment by xenova** [comment]
To get the exact same results, you can use the `unquantized` version (which is quite large at ~2GB):

```js
let pipe = await pipeline("text-classification", "Xenovabart-large-mnli", { quantized: false });
```

Just remember that it will take a bit longer to download the first time :).

If the model is too large, feel free to use one of the other models trained on MNLI: https://huggingface.co/models?pipeline_tag=zero-shot-classification&library=transformers.js&sort=trending

---

Alternatively, this might be due to bad default quantization settings. See [here](https://huggingface.co/docs/transformers.js/custom_usage#convert-your-models-to-onnx) for how to the conversion script. You may want to experiment with the `--per_channel` and `--reduce_range` options.
