### ISSUE TITLE
[Question] Getting a lot of ERR 404s when running in browser.

### ISSUE THREAD

**Issue by eklavyaisabird** [xenova/transformers.js#216]
When implementing code that accesses bart-large-mnli in the front-end part of my code, the browser console tells me every attempt to use the pipeline fails with an error 404. (at least that's what I think it's telling me)

So I am trying to use the bart-large-mnli to analyze a bunch of 'post' objects, and only display them if the text in the post relates to a selected 'interest'. 

Here is my javascript code to do that (checkRelevance.js):
```
import { pipeline } from "@xenova/transformers";

export default async function checkTweet(text, interest) {
  try {
    console.log(
      `checking tweet...\ntext:${text.substring(
        0,
        10
      )}...\ninterest:${interest}`
    );
    let pipe = await pipeline(
      "zero-shot-classification",
      "Xenova/bart-large-mnli",
      { quantized: false }
    );
    // console.log("await out...");
    let out = await pipe(text, interest);
    console.log(out);

    const relevant = out.scores[0] >= 0.5;
    console.log(out.scores[0]);
    return relevant;
  } catch (error) {
    console.log(error);
  }
}
```
And here is how it is implemented in the front end Feed.jsx:

```
useEffect(() => {
    setFilteredPosts(posts.map(post => {
       checkTweet(post.text, selectedInterest).then(result => {
        if (result) {
          return post
        }
      }
      )
    }))
  }, [selectedInterest]);

// ...

filteredPosts.map((post) => (
          <Post
            displayName={post.displayName}
            userName={post.userName}
            verified={post.verified}
            text={post.text}
            image={post.image}
            avatar={post.avatar}
          />) 

```

Now when I run checkRelevance.js on it's own with a small test, it accesses the api just fine, but when it's implemented in the browser I get this:
<img width="467" alt="Screen Shot 2023-07-25 at 5 40 40 PM" src="https://github.com/xenova/transformers.js/assets/77216995/6d693e09-d12d-4cfc-855d-7a764e0faca3">

and then this:
<img width="475" alt="Screen Shot 2023-07-25 at 5 41 06 PM" src="https://github.com/xenova/transformers.js/assets/77216995/50ad64c1-28b3-4469-8171-e652ecdc0a33">

I'm not asking you to debug all my code lol, just wondering if there's something extra that needs doing for running it in the browser.  If you need to see more lmk. Thanks!

**Comment by xenova** [comment]
The 404 error messages occur because (by design), we first check if the models are stored locally, before trying to download them from the Hugging Face hub. You can disable the local check by including the following code:

```js
import { env } from '@xenova/transformers';
env.allowLocalModels = false;
```

Unfortunately, browsers do not allow us to hide these errors (which are actually just warnings).


Regarding the second error, my guess is that the (unquantized) model is simply too large to be run in the browser, unfortunately. onnxruntime-web currently has a hard 2GB limit (due to it's dependence on protobuf), but there is [work being done to fix this](https://github.com/microsoft/onnxruntime/pull/16749).

If possible, I would recommend looking for a slightly smaller model (to be run in-browser) or switching to server-side inference.

**Comment by eklavyaisabird** [comment]
awesome, thank you!

**Comment by xenova** [comment]
Actually, looking back at your code - I think you might be able to get it working if you fix your `checkTweet` function. You are recreating the pipeline for each post! Also, you are not correctly disposing of the memory, which would very likely explain why you are running into memory issues.

**Comment by eklavyaisabird** [comment]
Based on the tutorial, using a worker.js file to have stuff run on a different thread and only recreating the pipeline when a parameter of the api call changes would help solve this? 
Also, I dont see how to dispose of memory anywhere in your tutorial, unless I missed it somehow?

**Comment by xenova** [comment]
> Based on the tutorial, using a worker.js file to have stuff run on a different thread and only recreating the pipeline when a parameter of the api call changes would help solve this?

Yes, you need to create a separate worker.js file and then use the `new Worker(...)` constructor to create a new web worker. Ideally, you will only have to create the pipeline once (that's the point of `useRef`).
```js
  // Create a reference to the worker object.
  const worker = useRef(null);

  // We use the `useEffect` hook to set up the worker as soon as the `App` component is mounted.
  useEffect(() => {
    if (!worker.current) {
      // Create the worker if it does not yet exist.
      worker.current = new Worker(new URL('./worker.js', import.meta.url), {
        type: 'module'
      });
    }

    // Create a callback function for messages from the worker thread.
    const onMessageReceived = (e) => { /* TODO: See tutorial */};

    // Attach the callback function as an event listener.
    worker.current.addEventListener('message', onMessageReceived);

    // Define a cleanup function for when the component is unmounted.
    return () => worker.current.removeEventListener('message', onMessageReceived);
  });
```

> Also, I dont see how to dispose of memory anywhere in your tutorial, unless I missed it somehow?

If you use the method I mention above, you don't need to worry about it (since you only create a single pipeline, which is deleted when you close the tab). If you want to control memory allocation, you can use `await pipeline.dispose()`.
