### ISSUE TITLE
Can this be used on Node?

### ISSUE THREAD

**Issue by gunta** [xenova/transformers.js#22]
I've tested on Node 18 and latest Bun, both don't work.

**Comment by xenova** [comment]
What errors are you getting? Others have had similar problems due to a bug in ONNX runtime web. Check out this thread for some fixes: https://github.com/xenova/transformers.js/issues/4

**Comment by epigramengineer** [comment]
I'm trying to run this on my sveltekit server code (instead of browser) with pretty much the documented setup:

```
import { pipeline } from "@xenova/transformers";


export const load: PageServerLoad = async ({ locals }) => {
  let pipe = await pipeline('summarization');
  let summary = await pipe("I am happy");

  return {
    summary
  };
};

```

And I'm getting the error:

```
TypeError: Cannot read properties of undefined (reading 'pipeline')
    at load (projects/web/src/routes/+page.server.ts:33:19)
    at Module.load_server_data (/node_modules/@sveltejs/kit/src/runtime/server/page/load_data.js:43:41)
    at /node_modules/@sveltejs/kit/src/runtime/server/page/index.js:141:18
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

If I move it into the page instead  of the server i get the same error, though maybe that's because of ssr?


Anyway super cool project you've got here I'm very excited to use it, I just have no idea what I'm doing in general lol

**Comment by xenova** [comment]
Hmm - for some reason it's not picking up the module. I assume you've installed it correctly (`npm i @xenova/transformers`)? I unfortunately haven't been able to test it in many different environments (such as sveltekit), so, I'm a little out-of-my-depth here. Perhaps someone else can provide some help?

> I just have no idea what I'm doing in general lol

*Same...* 🤣

**Comment by chelouche9** [comment]
Hi @epigramengineer,

I also ran into behaviors like that when using Next.js. I think that the library is trying to use some browser features. 
For me, it helped move the code into the code running on the client (like onClick of the button) and do the import dynamically.

```
export const onClick = async () => {
  const { pipeline } = await import("@xenova/transformers")
  let pipe = await pipeline('summarization');
  let summary = await pipe("I am happy");

  return {
    summary
  };
};
```

**Comment by xenova** [comment]
Great! Thanks for following up.

The `numThreads` fix is unfortunately necessary due to a bug in onnxruntime itself (https://github.com/microsoft/onnxruntime/issues/14445). Hopefully they will fix it soon. Otherwise, I might have to add a check to see if the user is running node, then override this value.

Closing the issue for now. Feel free to reopen/open a new issue if something else arises.

**Comment by wokutesh** [comment]
when I use the pipeline of @xenova/transformers in my project it return the error 'pipeline is undefined' my project is built in react using vite platform , I have already installed dependencies needed, so why it don't work

**Comment by xenova** [comment]
@wokutesh Feel free to open a new issue with more information. I'd be happy to assist.
