### ISSUE TITLE
[Question] Merge whisper-base.en main and output_attentions?

### ISSUE THREAD

**Issue by jozefchutka** [xenova/transformers.js#224]
I can see there is `output_attentions` branch on https://huggingface.co/Xenova/whisper-base.en/tree/main and the difference from `main` seems it can support `return_timestamps: 'word'`.

Is there a plan/schedule to merge these two?

Or these two branches are incompatible to be merged together? In such case, will both receive future updates?

**Comment by xenova** [comment]
The `output_attentions` branch should be backwards compatible, but I haven't done a thorough analysis on speed/accuracy improvements, which is why I have them separate for now.

Regarding updates, if I do update any, then yes they will both receive the same updates. This most likely won't be anything major (and may only be adding additional levels of quantization once ORT supports other than 8-bit quantization).

**Comment by jozefchutka** [comment]
My experiments comparing 2.2.0 and 2.4.3/output_attentions:

- speed completing transcription 11.76 sec vs. 12.23 (some ~4% slower)\
- speed when `"return_timestamps":"word"` 18.26
- accuracy of text is the same
- accuracy of timestamp is very similar with small differences like `27.36 -> 30.740000000000002` vs `27.36 -> 30.74` :-)


hope it helps

**Comment by xenova** [comment]
Good news - the two versions are now merged into main! (so you don't need to specify the revision anymore).

You'll also notice the model sizes are significantly smaller! See [here](https://twitter.com/xenovacom/status/1698742891118493905) for more details.
