### ISSUE TITLE
[Question] Adding Custom or Unused Token

### ISSUE THREAD

**Issue by hadminh** [xenova/transformers.js#239]
Is it possible to add custom range as a token?

For example for price_list of $100-$200

Can we add a custom vocab like this in vocab list

vocab list:
nice
hello
__$100-$200__
fish
...

**Comment by xenova** [comment]
Hi there. 👋  For the most part, this isn't something that this library (transformers.js) is focused on. You should rather do this from the transformers python library (https://github.com/huggingface/transformers) and then export your custom model to ONNX so that it can be used with transformers.js.

The [`tokenizer.add_tokens` function](https://huggingface.co/docs/transformers/internal/tokenization_utils#transformers.SpecialTokensMixin.add_tokens) (available in the python library) is probably what you are looking for.

**Comment by hadminh** [comment]
Thank you for your detailed response on how to approach these kinds of problems. I truly appreciate what you have accomplished on the JS side. Yes, it makes more sense to use the main library at the moment.

**Comment by hadminh** [comment]
Thank you for your detailed response on how to approach these kinds of problems. I truly appreciate what you have accomplished on the JS side. Yes, it makes more sense to use the main library at the moment.
