### ISSUE TITLE
Current use of execution providers is suboptimal

### ISSUE THREAD

**Issue by DavidGOrtega** [xenova/transformers.js#30]
Currently the library only operates with the WASM backend even in nodejs. However the better approach should be use [node bindings](https://www.npmjs.com/package/onnxruntime-node) in node and add the `webgl` EP to automatically fallback to `wasm` if `webgl` is not supported by the model.

Currenly in code:
```js
let session = await InferenceSession.create(buffer, {
  // executionProviders: ["webgl"]
  executionProviders: ["wasm"]
});
```

Hack to at least improve in the web
```js
let session;

try {
    session = await InferenceSession.create(buffer, {
        executionProviders: ['webgl', 'wasm']
    });
} catch (err) {
    session = await InferenceSession.create(buffer, {
        executionProviders: ['wasm']
    });
}
```

I can prepare a PR to improve the execution in node and web 😃

**Comment by DavidGOrtega** [comment]
related to https://github.com/xenova/transformers.js/issues/22 and #20

**Comment by xenova** [comment]
Hi! Yes, please do make a PR :) any contributions are most welcome.

I just had a question about webgl support for some of the models. When initially testing with the webgl backend, I kept getting errors saying that certain operations weren't supported. It might have been because the models are quantised (8-bit), but either way, I wasn't able to get it working reliably enough.

Do you have any suggestions?

**Comment by DavidGOrtega** [comment]
> Hi! Yes, please do make a PR :) any contributions are most welcome.

Good! Let's do it!



> Do you have any suggestions?

m open sourcing a project called aiui that transforms a model into an app, My first support was ONNX and it also happened to me. Not every layer is supported in webgl. It will depend on the model, but at least for the supported ones the speed will be very good.

Let me check what your script is doing.
