### ISSUE TITLE
[Feature request] LongT5 and Instructions!

### ISSUE THREAD

**Issue by santhosh97** [xenova/transformers.js#303]
Hey! I wanted to know what the process / requirements were to add new models to the repo. I was working with LongT5 and wanted to see if it was possible to get that added to the compatibility list.

Thanks!

**Comment by xenova** [comment]
Hi there! longt5 is indeed supported by [Optimum](https://github.com/huggingface/optimum), so it should be quite simple to add!

I'm in the process of improving the [contributing guide](https://github.com/xenova/transformers.js/pull/299), but in the meantime, you could search for references to t5 in the codebase, make copies for each class, and make suitable modifications to get it to work with longt5.

However, considering that I haven't made a solid contributing guide, you can also just list some existing longt5 models on the HF hub you would like to test, along with example usage code and output in the python transformers library, so that when we do add it, we can compare to make sure it's correct! 🤗

**Comment by xenova** [comment]
While writing the contributing guide, I started adding support for longt5 (which was very simple). I'm using it as a separate [PR](https://github.com/xenova/transformers.js/pull/316), to guide users in future if they want to add new models.

By the way, do you have any longt5 models that you would like to have ONNX models ready for? Most are just pre-trained models. I've tested with [this](https://huggingface.co/pszemraj/long-t5-tglobal-base-16384-book-summary) summarization model, and it does seem to operate correctly.

**Comment by naveengovind** [comment]
Would this work for translation models in long-t5 like this one https://huggingface.co/KETI-AIR-Downstream/long-ke-t5-base-translation-aihub-bidirection

**Comment by xenova** [comment]
> Would this work for translation models in long-t5 like this one https://huggingface.co/KETI-AIR-Downstream/long-ke-t5-base-translation-aihub-bidirection

Yes it should 👍 You can convert the model to ONNX with our [conversion script](https://github.com/xenova/transformers.js/blob/main/scripts/convert.py):
```
python -m scripts.convert --quantize --model_id KETI-AIR-Downstream/long-ke-t5-base-translation-aihub-bidirection
```
