### ISSUE TITLE
[Question | Bug] What am I doing wrong while using the `question-answering` model?

### ISSUE THREAD

**Issue by AyresMonteiro** [xenova/transformers.js#401]
## The Problem

I'm trying to use `question-answering` model to answer simple questions in a given context. But I always get a TypeError about floats. I guess that's an internal issue, because at top level of code I am not using floating point numbers. But maybe I am doing something wrong.

By the way, I'm using TypeScript and I was following the [docs for this model](https://huggingface.co/docs/transformers.js/api/pipelines#module_pipelines.QuestionAnsweringPipeline).

## Code

```ts
/** THIS CODE IS WRAPPED BY AN ASYNC FUNCTION */

const { pipeline } = await import("@xenova/transformers");

const answerer = await pipeline(
  "question-answering",
  "Xenova/distilbert-base-uncased-distilled-squad"
);

const results = await answerer(
  "Who is Dominic Toretto?",
  "Dominic Toretto is part of the family."
);
```

## Error

TypeError: A float32 tensor's data must be type of function Float32Array()

![image](https://github.com/xenova/transformers.js/assets/53703706/a248457f-e47a-4f42-8604-622bf8fe49ed)

![image](https://github.com/xenova/transformers.js/assets/53703706/a9f50b80-c9d6-4a83-aea7-908afd684759)

**Comment by xenova** [comment]
Hi there 👋 Could you maybe provide some more information about your environment? (e.g., node version, OS, bundler, etc). Running the piece of code on my side produces the correct results:
```
{ answer: 'part of the family', score: 0.778518732944228 }
```

Looking at the error alone, it reminds me of a bug in onnxruntime-web, when using Jest (see https://github.com/microsoft/onnxruntime/issues/16622 and https://github.com/jestjs/jest/issues/11864), and I believe this is also the issue here. Fortunately, there are workarounds available in those threads - and in fact, we use them in our [unit tests](https://github.com/xenova/transformers.js/blob/main/tests/init.js#L11-L67) too.

**Comment by AyresMonteiro** [comment]
> Looking at the error alone, it reminds me of a bug in onnxruntime-web when using Jest (see [microsoft/onnxruntime#16622](https://github.com/microsoft/onnxruntime/issues/16622) and [jestjs/jest#11864](https://github.com/jestjs/jest/issues/11864)), and I believe this is also the issue here. Fortunately, there are workarounds available in those threads - and in fact, we use them in our [unit tests](https://github.com/xenova/transformers.js/blob/main/tests/init.js#L11-L67) too.

Thanks! I was really using Jest and the workaround worked for me!

I'm closing this issue.
