### ISSUE TITLE
[Question] Does any version support Node 14

### ISSUE THREAD

**Issue by Ncifra** [xenova/transformers.js#412]
Hi,

I have tried downgrading the library to version 2, and even to 1, but that one was missing types.

Is there some way to be able to use it with Node 14? I have seen that mostly the issues are with nullish coalescing characters, so wanted to make sure if there could be other issues that tie it to Node 18+, and also if there have been any security and vulnerability issues from said version (that could work with Node 14).

Thanks

**Comment by xenova** [comment]
There are quite a few other issues that are caused by versions < 18, including missing support for `fetch`, `Request`, and other functions/classes which are now built-in. Node 14 reached EOL on April 30, 2023, and I don't see that it's worth adding backwards compatibility support for it.

And to answer your other question, the library was developed (and tested) in an Node 18+ environment since the beginning, so I don't think there will be any version that properly supports Node 14. If it is very important that you can only use Node 14, then feel free to fork the project and make the necessary modifications/removals.
