### ISSUE TITLE
AutomaticSpeechRecognitionPipeline callback_function api inconsistancy

### ISSUE THREAD

**Issue by j0rd1smit** [xenova/transformers.js#43]
In the `AutomaticSpeechRecognitionPipeline` class the `callback_function` is used in two places:
1. [To return the chucks](https://github.com/xenova/transformers.js/blob/4b1d135228bccc1019a0233a72eb2a41b12471fb/src/pipelines.js#LL484C6-L484C6)
2. [In the model generation](https://github.com/xenova/transformers.js/blob/4b1d135228bccc1019a0233a72eb2a41b12471fb/src/models.js#L586)

As a result, 1 returns a different data format than 2. This wasn't very clear to me. Does it not make sense to have a separate callback for these?

**Comment by j0rd1smit** [comment]
(BTW I love how fast you are responding to issues here kudos 😀)

**Comment by xenova** [comment]
> (BTW I love how fast you are responding to issues here kudos 😀)

Haha yeah I'm trying my best to get all these things fixed! 😄  I'm online 24/7 ;)

> Yeah, I really like the stream part, so keep it. I would keep calling the streaming callback callback_function to stay consistent. chunk_callback makes sense here since it is only used in the chuck callback.

Okay that sounds do-able. This functionality (streaming while doing merging) isn't available in the python implementation, so, there aren't any "rules" to follow per-se (other than it should make sense haha).

> callback_function would then render the initial results, while chunk_callback obtains the final result and adds the timestamps. (I'm not sure if this directly works since you need all the chucks so far for timestamps if you use  pipeline.tokenizer._decode_asr(chunks, ...). I think the chunk_callback only receives the newly generated chucks. However, this is fixable by keeping track of all the states yourself in the callback).

Technically, it is possible to get the timestamps while you are generating, using a combination of the `callback_function` and `pipeline.tokenizer._decode_asr(chunks, ...)`, with `force_full_sequences=false`. This would entail keeping track of all the output tokens as you generate, and you can detect a "new chunk" if the output token you get is the `<|startoftranscript|>` token. Then, you can perform the merging as you generate new tokens. The `force_full_sequences=false` is necessary, otherwise it will through an error because the whole transcript isn't ready yet.

I can try provide an example (later possibly), but I am currently working on fixing some other bugs (see other issues).

**Comment by xenova** [comment]
Updated in https://github.com/xenova/transformers.js/commit/6c9ea41970462da863b4a3a83a15c89b682117dd 👍 

will close the issue when I make the 1.3.2 release.

Let me know if you have any other questions or suggestions :)

**Comment by xenova** [comment]
Update is now live! (https://www.npmjs.com/package/@xenova/transformers/v/1.3.2)

Closing the issue now :)
