### ISSUE TITLE
[Model request] DETR / OWLVIT

### ISSUE THREAD

**Issue by TheFlashBold** [xenova/transformers.js#44]
Normal VIT seems to struggle in my test, maybe these are better for object-detection?
- DETR https://huggingface.co/docs/transformers/model_doc/detr
- OWL-VIT https://huggingface.co/docs/transformers/model_doc/owlvit

**Comment by xenova** [comment]
Hi! Thanks for the suggestion. This definitely sounds do-able!

My only concern at the moment would be execution speed, since, the library only supports WASM/CPU backends. WebGPU backend is coming soon though, so, it probably would be a good idea to get started! :)

Could you perhaps provide code snippets / examples for how you intend to use the model? Also, could you explain in more detail what is wrong with the normal VIT? (Perhaps it is too large, and hence, slow?)

**Comment by xenova** [comment]
Good news! We added support for object detection w/ DETR in v1.3.3 🎉 

Demo:

https://user-images.githubusercontent.com/26504141/227374871-51df198d-daab-40bb-8ac5-e1afebacc296.mp4

---

Example usage:
```javascript
// npm i @xenova/transformers
import { pipeline } from '@xenova/transformers';

// Allocate object detection pipeline
// (uses 'facebook/detr-resnet-50' by default)
let detector = await pipeline('object-detection');

// Specify image
let img = 'https://xenova.github.io/transformers.js/assets/images/cats.jpg';

let predictions = await detector(img, {
    threshold: 0.9 // default is 0.5
});
```

which will output:
```json
{
  "boxes": [
    [30.09, 68.47, 187.94, 118.53],
    [329.51, 66.39, 370.07, 192.87],
    [-2.80, 0.13, 636.90, 472.21],
    [6.57, 53.89, 321.98, 468.69],
    [331.87, 21.79, 648.55, 369.94]
  ],
  "classes": [75, 75, 63, 17, 17],
  "scores": [0.998, 0.996, 0.995, 0.998, 0.999],
  "labels": ["remote", "remote", "couch", "cat", "cat"]
}
```

---

I will close the issue for now, but we may add owlvit in future.
