### ISSUE TITLE
[Feature request] Change default text generation model from gpt2 to distilgpt2

### ISSUE THREAD

**Issue by chelouche9** [xenova/transformers.js#45]
Currently, the default model is gpt2 for text generation. It isn't good and I could not configure it to work correctly.

I used distilgpt2 and it works great out of the box. I want to create a PR and change it. @xenova What do you think?

**Comment by xenova** [comment]
The only reason I use gpt2 as the default, is because HF uses it as a default:

https://github.com/huggingface/transformers/blob/5fd4e3c87c685fba2dd9615be62131748a8b5ee3/src/transformers/pipelines/__init__.py#LL280

I think default performance might improve once I add more generation parameters (no repeat n grams, etc.)

**Comment by xenova** [comment]
> I think default performance might improve once I add more generation parameters (no repeat n grams, etc.)

We recently added `repetition_penalty` and `no_repeat_ngram_size` generation parameters by the way :)
