### ISSUE TITLE
Incorrect model_max_length for some e5 model variants

### ISSUE THREAD

**Issue by fralik** [xenova/transformers.js#456]
### System Info

transformers.js 2.10.1

### Environment/Platform

- [ ] Website/web-app
- [ ] Browser extension
- [ ] Server-side (e.g., Node.js, Deno, Bun)
- [ ] Desktop app (e.g., Electron)
- [ ] Other (e.g., VSCode extension)

### Description

If you look at tokenizer config file in E5 models, then you can see that `model_max_length` is too big. I believe it should be 512.

See:
https://huggingface.co/Xenova/e5-small-v2/blob/main/tokenizer_config.json
https://huggingface.co/Xenova/e5-small/blob/main/tokenizer_config.json

Compare with:
https://huggingface.co/Xenova/e5-large-v2/blob/main/tokenizer_config.json
https://huggingface.co/Xenova/e5-base-v2/blob/main/tokenizer_config.json

### Reproduction

See the links in the description.

**Comment by xenova** [comment]
Thanks for pointing this out. I've updated the configs. :+1: The reason why it was set that way is because those were the values set by the original model author at the time of conversion (they were [updated](https://huggingface.co/intfloat/e5-small-v2/commit/dca8b1a9dae0d4575df2bf423a5edb485a431236) later).
