### ISSUE TITLE
Library no longer maintained?

### ISSUE THREAD

**Issue by pax-k** [xenova/transformers.js#646]
### Question

1 year has passed since this PR is ready for merge: [Support React Native #118](https://github.com/xenova/transformers.js/pull/118)

Should we do our own fork of xenova/transformers.js ?

**Comment by osanseviero** [comment]
Given last release was last week, I think it's still actively maintained. Take a look at https://github.com/xenova/transformers.js/releases

**Comment by xenova** [comment]
@pax-k I encourage you to check out the v3 branch: https://github.com/xenova/transformers.js/pull/545. At the moment, we are prioritizing WebGPU support over React Native support, but I can assure you that the latter will come, eventually.

**Comment by xenova** [comment]
Thank you for your kind words @hans00, and I appreciate your patience! We're also in contact with the `onnxruntime-react-native` team and we'll be prioritizing React Native support once WebGPU support has been completed.

Closing this issue, since the library is most certainly still being "maintained" 😉

**Comment by jpcoder2** [comment]
@hans00, I'm thinking that the NativeEventsEmitter error is because of one of the dependencies that is not compatible with the current version of Expo.

There any way you could create a new sample app that uses the current version of React Native+Expo?
