### ISSUE TITLE
Is it possible to run a music / sounds generation model?

### ISSUE THREAD

**Issue by flatsiedatsie** [xenova/transformers.js#668]
### Question

I'd love to create a browser-based music generation tool, or one that can turn text into sound effects. Is that supported?

I guess my more general question is: can Transformers.js run pretty much any .onnx I throw at it, or does each model require some level of implementation before it can be used?

**Comment by flatsiedatsie** [comment]
Well would you look at that plot thickening: https://huggingface.co/Xenova/musicgen-small

Except.. that the repo was created a day ago. Whoa.

**Comment by xenova** [comment]
Yep! Somehow your feature request came at the perfect time! This is something I've been working on already for a few days. This is all now possible thanks to [this PR](https://github.com/huggingface/optimum/pull/1779) by @fxmarty.

Stay tuned for updates! This might only be available in [v3](https://github.com/xenova/transformers.js/pull/545) due to WebGPU support (I think CPU/WASM-only will be too slow).

**Comment by fxmarty** [comment]
I did not implement it in the PR yet, I'll maybe do it with ONNX Runtime (patching some transformers methods to use ORT instead of torch)

**Comment by flatsiedatsie** [comment]
I have no idea what that means, except that I should be patient :-)

**Comment by flatsiedatsie** [comment]
Whoop! https://github.com/xenova/transformers.js/pull/545#issuecomment-2041205108

**Comment by flatsiedatsie** [comment]
- It's now possible! e.g. https://flatsiedatsie.github.io/transformers_js_musicgen/
