### ISSUE TITLE
Text completion fails with non-default model passed in as argument

### ISSUE THREAD

**Issue by spencekim** [xenova/transformers.js#7]
When trying to use the flan-t5-base model in place of the default model text-completion, the pipeline fails:

`Error: File not found. Could not locate "/models/onnx/quantized/google/flan-t5-base/causal-lm-with-past/tokenizer_config.json".`

**Comment by spencekim** [comment]
Closing this after seeing in the docs that FLAN-T5 is used for seq-to-seq tasks only

**Comment by xenova** [comment]
Hi! It appears as though you are using the the wrong pipeline. You should be using "text2text-generation" instead of "text-generation".

This is because FLAN-T5 is a "text2text generation" model, as opposed to a "text generation model".

For example, see the tags of the models:
1. FLAN-T5: https://huggingface.co/google/flan-t5-base (text2text generation)
2. GPT2: https://huggingface.co/gpt2 (text generation)

**Comment by spencekim** [comment]
Oops, I meant to close this issue but looks like I clicked the button twice last night. Sorry about that 👍
