### ISSUE TITLE
[Bug] Output of CLIP tokenizer is different from huggingface/transformers one

### ISSUE THREAD

**Issue by pink-red** [xenova/transformers.js#74]
**Describe the bug**
*A clear and concise description of what the bug is.*

The returned tokens in `input_ids` are different between CLIP tokenizers from transformers.js and huggingface/transformers.

**How to reproduce**
*Steps or a minimal working example to reproduce the behavior*

Python:
```python
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("openai/clip-vit-large-patch14")
print(tokenizer("this is a test string of text")["input_ids"])

# output: [49406, 589, 533, 320, 1628, 9696, 539, 4160, 49407]
```

JavaScript:
```javascript
import { AutoTokenizer } from "@xenova/transformers"

AutoTokenizer.from_pretrained(
  "https://huggingface.co/openai/clip-vit-large-patch14/resolve/main"
).then((tokenizer) => {
  console.log(tokenizer("this is a test string of text").input_ids)
})

// output: [49406n, 4340n, 595n, 64n, 7738n, 25512n, 684n, 18169n, 49407n]
```

**Expected behavior**
*A clear and concise description of what you expected to happen.*

The returned tokens should be the same as in the Python version.

**Logs/screenshots**
*If applicable, add logs/screenshots to help explain your problem.*

**Environment**
- Transformers.js version: 1.4.1
- Browser (if applicable): Firefox 111.0.1
- Operating system (if applicable):
- Other:

**Additional context**
*Add any other context about the problem here.*

I'm not really sure if it's actually a bug, maybe the tokenizer should be used a bit differently to get the same output?

By the way, it's great to see a JS implementation of the transformers library, it's very helpful!

**Comment by xenova** [comment]
Hi! Thanks for the report. The output *should* be the exact same as the Python library, so there is bug 😅 

Looks like it should be a (relatively) simple fix, as I seem to have forgotten to use the `end_of_word_suffix` which is in the config.

Will push an update when I've fixed it!

**Comment by xenova** [comment]
That said, you do identify an annoying problem I have with the python implementation... That they have the same code repeated everywhere, with sometimes very little modifications. For example, the clip tokenizer's bpe method is modified slightly to include the end_of_word_suffix, while other bpe methods don't have that :/ (which is why I didn't have `</w` supported for the clip tokenizer)

ClipTokenizer

https://github.com/huggingface/transformers/blob/656e869a4523f6a0ce90b3aacbb05cc8fb5794bb/src/transformers/models/clip/tokenization_clip.py#L427

Other: https://github.com/huggingface/transformers/blob/656e869a4523f6a0ce90b3aacbb05cc8fb5794bb/src/transformers/models/bart/tokenization_bart.py#L248

**Comment by xenova** [comment]
Fixed in https://github.com/xenova/transformers.js/commit/f0e47a85362853599580c0511097126ca9e9c1e1 👍 

Will publish a full release soon too.
