### ISSUE TITLE
Can I use Xenova/Phi-3-mini-4k-instruct model server side?

### ISSUE THREAD

**Issue by StepanKukharskiy** [xenova/transformers.js#789]
### Question

Hey there! I’m trying to run Xenova/Phi-3-mini-4k-instruct model using transformers.js 2.17.2 on the server in my Node.js project, but I get an error saying that Phi-3 is not supported. Can I make it work somehow? Any ideas appreciated

**Comment by xenova** [comment]
Phi-3 models are only supported in the v3 dev branch: https://github.com/xenova/transformers.js/pull/545. You can find example code [here](https://github.com/xenova/transformers.js/tree/v3/examples/webgpu-chat). However, we haven't yet finished adding support for server-side usage, since that requires extra consideration for the external data format.

**Comment by StepanKukharskiy** [comment]
Got it! Thanks a lot!
